import { Car } from '../../types';

export const mockCars: Car[] = [
  {
    id: 'car-1',
    slug: 'tata-nexon',
    brand: 'Tata',
    model: 'Nexon',
    fullName: 'Tata Nexon',
    exShowroomPrice: 810000,
    priceRange: '₹8.10L - ₹15.60L',
    rating: 4.3,
    reviewCount: 2140,
    fuelType: 'Diesel / Petrol / Electric',
    transmission: 'Manual / Automatic',
    bodyType: 'SUV',
    seats: 5,
    imagePlaceholder: 'Tata Nexon Studio Shot 3/4 View',
    isNewLaunch: false,
    isTrending: true
  },
  {
    id: 'car-2',
    slug: 'hyundai-creta',
    brand: 'Hyundai',
    model: 'Creta',
    fullName: 'Hyundai Creta',
    exShowroomPrice: 1100000,
    priceRange: '₹11.00L - ₹20.15L',
    rating: 4.5,
    reviewCount: 3450,
    fuelType: 'Diesel / Petrol',
    transmission: 'Manual / Automatic',
    bodyType: 'SUV',
    seats: 5,
    imagePlaceholder: 'Hyundai Creta Studio Shot 3/4 View',
    isNewLaunch: false,
    isTrending: true
  },
  {
    id: 'car-3',
    slug: 'mahindra-xuv700',
    brand: 'Mahindra',
    model: 'XUV700',
    fullName: 'Mahindra XUV700',
    exShowroomPrice: 1399000,
    priceRange: '₹13.99L - ₹26.99L',
    rating: 4.6,
    reviewCount: 1890,
    fuelType: 'Diesel / Petrol',
    transmission: 'Manual / Automatic',
    bodyType: 'SUV',
    seats: 7,
    imagePlaceholder: 'Mahindra XUV700 Studio Shot 3/4 View',
    isNewLaunch: false,
    isTrending: true
  },
  {
    id: 'car-4',
    slug: 'kia-seltos',
    brand: 'Kia',
    model: 'Seltos',
    fullName: 'Kia Seltos',
    exShowroomPrice: 1090000,
    priceRange: '₹10.90L - ₹20.35L',
    rating: 4.4,
    reviewCount: 1250,
    fuelType: 'Diesel / Petrol',
    transmission: 'Manual / Automatic',
    bodyType: 'SUV',
    seats: 5,
    imagePlaceholder: 'Kia Seltos Studio Shot 3/4 View',
    isNewLaunch: false,
    isTrending: false
  },
  {
    id: 'car-5',
    slug: 'honda-city',
    brand: 'Honda',
    model: 'City',
    fullName: 'Honda City',
    exShowroomPrice: 1182000,
    priceRange: '₹11.82L - ₹16.35L',
    rating: 4.4,
    reviewCount: 980,
    fuelType: 'Petrol / Hybrid',
    transmission: 'Manual / Automatic',
    bodyType: 'Sedan',
    seats: 5,
    imagePlaceholder: 'Honda City Studio Shot 3/4 View',
    isNewLaunch: false,
    isTrending: false
  },
  {
    id: 'car-6',
    slug: 'mg-windsor-ev',
    brand: 'MG',
    model: 'Windsor EV',
    fullName: 'MG Windsor EV',
    exShowroomPrice: 1350000,
    priceRange: '₹13.50L - ₹15.50L',
    rating: 4.2,
    reviewCount: 310,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Hatchback',
    seats: 5,
    imagePlaceholder: 'MG Windsor EV Studio Shot 3/4 View',
    isNewLaunch: true,
    isTrending: true
  }
];
