'use client';
import React, { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { CarDetailAggregate } from '../../types/vehicle';
import { calculateEMIDetails, calculateAmortizationSchedule } from '../../lib/calculations/emi';
import { getAllCities, getCityPrice, getAllModels, getAllMakes } from '../../lib/data/cars-db';
import { SectionHeader, MetricStrip, SpecTable, InteractiveSlider, currency, lakh, specValue, VehicleCard } from '../design/Primitives';

export interface CarShowroomProps { initialData: CarDetailAggregate; topic?: string; }
const topics = ['overview','variants','specs','price','images','reviews','mileage','safety','verdict','similar','enquiry'];
const extras = [{ name:'Zero depreciation', price:8500 },{ name:'Engine protection',price:4200 },{ name:'Return to invoice',price:5100 },{ name:'Extended warranty',price:14000 }];

export const CarShowroom: React.FC<CarShowroomProps> = ({ initialData, topic = 'overview' }) => {
  const { make, model, variants, rivals, reviews } = initialData;
  const cities = getAllCities();
  const [city,setCity] = useState(initialData.selectedCity);
  const [variant,setVariant] = useState(initialData.selectedVariant);
  const [imageIndex,setImageIndex] = useState(0);
  const [activeSection,setActiveSection] = useState(topic);
  const [addOns,setAddOns] = useState([true,true,false,false]);
  const [downPayment,setDownPayment] = useState(20);
  const [years,setYears] = useState(5);
  const [interest,setInterest] = useState(9.5);
  const [dailyKm,setDailyKm] = useState(35);
  const [zoom,setZoom] = useState(false);
  const galleryDialog = useRef<HTMLDialogElement>(null);
  const touchStart = useRef(0);
  const modelNav = useRef<HTMLElement>(null);
  const gallery = model.galleryImages.length ? model.galleryImages.filter(item => item.type === 'image') : [{ id:'hero',url:model.heroImage,altText:`${make.name} ${model.name}`,colorName:undefined }];
  const currentImage = gallery[imageIndex] || gallery[0];
  const moveImage = (delta:number) => { setImageIndex(index => (index + delta + gallery.length) % gallery.length); setZoom(false); };
  const price = getCityPrice(variant,city);
  const addOnTotal = extras.reduce((sum,extra,i) => sum + (addOns[i] ? extra.price : 0),0);
  const onRoad = price.onRoadPrice + addOnTotal;
  const downAmount = Math.round(onRoad * downPayment / 100);
  const emi = calculateEMIDetails(onRoad,downAmount,interest,years*12);
  const schedule = calculateAmortizationSchedule(emi.loanAmount,interest,years*12);
  const isElectric = variant.fuelType === 'Electric';
  const [energyRate,setEnergyRate] = useState(isElectric ? 9 : 102);
  const [evEfficiency,setEvEfficiency] = useState(6.5);
  const efficiency = isElectric ? evEfficiency : variant.mileageKmpl;
  const monthlyFuel = efficiency ? Math.round(dailyKm * 30 / efficiency * energyRate) : null;
  const service = [3500,5200,6800,8500,9200];
  const insuranceFactors = [1,.78,.65,.55,.48];
  const renewalInsurance = insuranceFactors.slice(1).reduce((sum,factor) => sum + Math.round(price.insurance*factor),0);
  const serviceTotal = service.reduce((a,b) => a+b,0);
  const ownership = monthlyFuel === null ? null : onRoad + monthlyFuel*60 + renewalInsurance + serviceTotal;
  const basePath = `/cars/${make.slug}/${model.slug}`;
  useEffect(() => {
    let frame = 0;
    const updateSection = () => {
      const sections = [...topics, 'tco', 'emi', 'rivals', 'faqs'].map(id => ({ id, top:document.getElementById(id)?.getBoundingClientRect().top ?? Infinity })).filter(section => section.top <= 220).sort((a,b) => b.top-a.top);
      if(sections[0]) setActiveSection(sections[0].id);
      frame = 0;
    };
    const onScroll = () => { if(!frame) frame = requestAnimationFrame(updateSection); };
    window.addEventListener('scroll',onScroll,{passive:true});
    return () => { window.removeEventListener('scroll',onScroll); cancelAnimationFrame(frame); };
  }, []);
  useEffect(() => {
    const rail = modelNav.current?.firstElementChild as HTMLElement | undefined;
    const selected = rail?.querySelector<HTMLElement>('[aria-current]');
    if (!rail || !selected || (modelNav.current?.getBoundingClientRect().top ?? Infinity) > 74) return;
    const left = selected.offsetLeft - rail.offsetLeft;
    if(left < rail.scrollLeft || left + selected.offsetWidth > rail.scrollLeft + rail.clientWidth) rail.scrollLeft = Math.max(0,left-24);
  }, [activeSection]);
  return <div className="dossier">
    <div className="kerb-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/cars">Cars</Link><span>/</span><Link href={`/cars/${make.slug}`}>{make.name}</Link><span>/</span><span>{model.name}</span>{topic !== 'overview' && <><span>/</span><span>{topic}</span></>}</nav>
      <section className="dossier-hero" id="overview" aria-labelledby="model-title">
        <div className="hero-photo"><Image src={model.heroImage} alt={`${make.name} ${model.name}`} fill priority sizes="(max-width: 800px) 100vw, 65vw" /><button onClick={() => galleryDialog.current?.showModal()} className="photo-open">Explore gallery ↗</button><span className="photo-index">01 / {String(gallery.length).padStart(2,'0')}</span></div>
        <div className="hero-context"><span className="eyebrow">The vehicle dossier / {model.bodyType}</span><h1 id="model-title">{make.name}<br/><strong>{model.name}</strong>{topic !== 'overview' && <small>{topic === 'specs' ? 'Specifications' : topic}</small>}</h1><div className="hero-price">{lakh(model.priceRangeMin)}–{lakh(model.priceRangeMax)}<small>Lakh · Ex-showroom</small></div><div className="hero-trust"><span className="rating">★ {model.rating} / 5 <small>Listed rating</small></span><span data-tone="safety">{model.safetyRating.stars}★ <small>{model.safetyRating.agency}</small></span></div><div className="actions"><a href="#variants" className="action">View variants ↗</a><a href="#emi" className="action secondary">Calculate EMI</a></div><p className="data-note">{initialData.currentGeneration.name} · {initialData.currentGeneration.startYear}–present</p></div>
      </section>
      <MetricStrip items={[{label:'Power',value:`${variant.powerBhp} bhp`},{label:'Torque',value:`${variant.torqueNm} Nm`},{label:isElectric?'Claimed range':'Claimed mileage',value:isElectric ? variant.rangeKm ? `${variant.rangeKm} km` : 'Data unavailable' : variant.mileageKmpl ? `${variant.mileageKmpl} km/l` : 'Data unavailable',tone:'efficiency'},{label:'Ground clearance',value:specValue(model,/ground clearance/i)},{label:'Boot space',value:specValue(model,/boot/i)},{label:'Seats',value:String(variant.seating)}]} />
    </div>
    <nav ref={modelNav} className="model-nav" aria-label="Model sections"><div className="kerb-shell">{topics.map(item => <a key={item} href={`#${item}`} aria-current={activeSection === item ? 'location' : undefined} onClick={() => setActiveSection(item)}>{item === 'specs' ? 'Specifications' : item.charAt(0).toUpperCase()+item.slice(1)}</a>)}</div></nav>
    <div className="kerb-shell">
      <section id="price" className="chapter" data-tone="financial"><SectionHeader index="01" label="Pricing" title="The price. And the whole picture." description="Choose your city and variant for an itemised on-road estimate." tone="financial"/><div className="split-analysis"><div><div className="price-controls"><label>City<select aria-label="Pricing city" value={city.slug} onChange={e => setCity(cities.find(c => c.slug === e.target.value)!)}>{cities.map(c => <option key={c.id} value={c.slug}>{c.name}</option>)}</select></label><label>Variant<select aria-label="Pricing variant" value={variant.id} onChange={e => { const next = variants.find(v => v.id === e.target.value)!; setVariant(next); setEnergyRate(next.fuelType === 'Electric'?9:102); }}>{variants.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div><p className="eyebrow price-eyebrow">Ex-showroom / {variant.name}</p><div className="big-number">{currency(variant.exShowroomPrice)}</div><p className="data-note">{price.id.startsWith('calc-') ? 'Estimated from the stored city tax formula.' : `Database quote · ${price.source} · ${price.lastVerifiedAt}`}</p><table className="data-table city-prices"><caption className="sr-only">City on-road estimates excluding optional extras</caption><tbody>{cities.slice(0,3).map(c => <tr key={c.id}><th scope="row"><Link href={`${basePath}/${c.slug}?variant=${variant.slug}`}>{c.name}</Link></th><td>{currency(getCityPrice(variant,c).onRoadPrice)}<small>Estimated on-road</small></td></tr>)}</tbody></table><details className="add-ons"><summary>Optional protection <span>+ {currency(addOnTotal)}</span></summary>{extras.map((extra,i) => <label key={extra.name}><input type="checkbox" checked={addOns[i]} onChange={e => setAddOns(previous => previous.map((value,index) => index === i ? e.target.checked : value))}/><span>{extra.name}</span><span>{currency(extra.price)}</span></label>)}<p className="data-note">Illustrative add-on costs; actual provider quotes may differ.</p></details></div><div className="receipt"><span className="eyebrow">On-road estimate / {city.name}</span><dl>{[['Ex-showroom',price.exShowroom],['RTO / road tax',price.rtoTax],['Insurance',price.insurance],['FASTag',price.fastag],['Handling',price.handlingCharges],['Optional protection',addOnTotal]].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{currency(Number(value))}</dd></div>)}<div className="receipt-total"><dt>Total on-road</dt><dd>{currency(onRoad)}</dd></div></dl><p className="data-note">Estimated total including selected extras. Final invoice depends on the dealer and insurance provider.</p><a href="#emi" className="text-link">Plan monthly payments →</a></div></div></section>
      <section id="variants" className="chapter"><SectionHeader index="02" label="Variants" title="Find your fit in the range." description="Select a trim to update pricing, key specifications and finance. KERB picks are editorial recommendations."/><div className="table-scroll" tabIndex={0} role="region" aria-label="Variant decision table"><table className="data-table variant-table"><thead><tr>{['Variant','Ex-showroom','Powertrain','Key features','Who it’s for'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{variants.map(v => <tr key={v.id} className={v.id===variant.id?'selected-variant':''}><th scope="row"><button aria-pressed={v.id===variant.id} onClick={() => { setVariant(v); setEnergyRate(v.fuelType==='Electric'?9:102); }}>{v.id===variant.id?'✓ ':''}{v.name}</button>{v.isRecommended && <span className="kerb-pick">KERB PICK</span>}</th><td className="money">{lakh(v.exShowroomPrice)} Lakh</td><td>{v.fuelType}<br/><span className="muted">{v.transmission} · {v.powerBhp} bhp</span></td><td><ul>{v.keyFeatures.map(feature => <li key={feature}>{feature}</li>)}</ul></td><td>{v.recommendationReason || v.badge || 'Recommendation unavailable'}</td></tr>)}</tbody></table></div></section>
      <section id="specs" className="chapter" data-tone="technical"><SectionHeader index="03" label="Technical dossier" title="Every detail. In plain sight." description={`Selected trim: ${variant.name}. Model-level reference data is listed separately below.`}/><nav className="spec-jumps" aria-label="Specification categories"><a href="#selected-specs">Selected variant</a>{model.specifications.map((group,index) => <a href={`#spec-group-${index}`} key={group.title}>{group.title}</a>)}</nav><div id="selected-specs"><SpecTable title={`${variant.name} / selected variant`} items={[{name:'Fuel',value:variant.fuelType},{name:'Displacement',value:variant.engineCc?`${variant.engineCc} cc`:'Data unavailable'},{name:'Max power',value:`${variant.powerBhp} bhp`},{name:'Max torque',value:`${variant.torqueNm} Nm`},{name:'Transmission',value:variant.transmission},{name:'Seating',value:String(variant.seating)},{name:'Airbags',value:String(variant.airbags)}]}/></div><p className="data-note">Model reference specifications · equipment and powertrains may differ by variant.</p><div className="spec-layout">{model.specifications.map((group,index) => <div id={`spec-group-${index}`} key={group.title}><SpecTable title={group.title} items={group.items}/></div>)}</div></section>
      <section id="safety" className="chapter" data-tone="safety"><SectionHeader index="04" label="Safety" title="Protection, explained." tone="safety"/><div className="safety-layout"><div className="safety-score"><strong>{model.safetyRating.stars}<small>/ 5</small></strong><span aria-label={`${model.safetyRating.stars} out of 5 stars`}>{'★'.repeat(model.safetyRating.stars)}{'☆'.repeat(5-model.safetyRating.stars)}</span><p>{model.safetyRating.agency}</p><small>Rating listed in vehicle database</small></div><div><dl className="finance-lines"><div><dt>Adult occupant protection</dt><dd>{model.safetyRating.adultScore || 'Data unavailable'}</dd></div><div><dt>Child occupant protection</dt><dd>{model.safetyRating.childScore || 'Data unavailable'}</dd></div><div><dt>Safety assist score</dt><dd>Data unavailable</dd></div><div><dt>Airbags · selected variant</dt><dd>{variant.airbags}</dd></div></dl><p className="data-note">Model rating; check the tested variant and test protocol with {model.safetyRating.agency}.</p></div></div>{model.specifications.filter(group => /safety/i.test(group.title)).map(group => <SpecTable key={group.title} title="Safety equipment / model reference" items={group.items}/>)}</section>
      <section id="mileage" className="chapter" data-tone="efficiency"><SectionHeader index="05" label="Efficiency" title={isElectric?'Range and running costs.':'What will your commute cost?'} tone="efficiency" description="Manufacturer claims and your estimates are separate from measured road-test results."/><MetricStrip items={[{label:isElectric?'Manufacturer claimed range':'Manufacturer claimed mileage',value:isElectric ? variant.rangeKm?`${variant.rangeKm} km`:'Data unavailable' : variant.mileageKmpl?`${variant.mileageKmpl} km/l`:'Data unavailable',tone:'efficiency'},{label:'KERB tested',value:'Data unavailable',tone:'efficiency'},{label:'Owner reported',value:reviews.find(r => r.mileageReported)?.mileageReported || 'Data unavailable',tone:'efficiency'}]}/><div className="split-analysis tool-space" id="commute"><div><h3>Monthly {isElectric?'charging':'fuel'} calculator</h3><InteractiveSlider id="daily-distance" label="Daily distance" value={dailyKm} display={`${dailyKm} km / day`} min={10} max={120} step={5} onChange={setDailyKm}/><InteractiveSlider id="energy-rate" label={isElectric?'Electricity rate assumption':'Fuel price assumption'} value={energyRate} display={`₹${energyRate} / ${isElectric?'kWh':'litre'}`} min={isElectric?1:50} max={isElectric?30:150} onChange={setEnergyRate}/>{isElectric && <InteractiveSlider id="ev-efficiency" label="Efficiency assumption" value={evEfficiency} display={`${evEfficiency} km/kWh`} min={2} max={10} step={.1} onChange={setEvEfficiency}/>}<p className="data-note">Estimate uses 30 driving days per month and {isElectric?'your efficiency assumption': 'the selected variant’s claimed efficiency'}. Driving conditions change actual consumption.</p></div><div className="finance-result"><span className="eyebrow">Estimated monthly cost</span><div className="big-number" aria-live="polite">{monthlyFuel===null?'Data unavailable':currency(monthlyFuel)}</div><p className="data-note">{dailyKm*30} km / month{monthlyFuel!==null && ` · ${currency(monthlyFuel/(dailyKm*30))} / km`}</p>{monthlyFuel!==null && <div className="cost-scale"><span style={{width:`${Math.min(100,dailyKm/120*100)}%`}}/><small>{currency(monthlyFuel*12)} estimated annual cost</small></div>}</div></div></section>
      <section id="tco" className="chapter" data-tone="financial"><SectionHeader index="06" label="Ownership cost" title="Look beyond the sticker price." tone="financial" description={`Five-year estimate at ${(dailyKm*30*60).toLocaleString('en-IN')} km, using your commute settings. Service and renewal assumptions are illustrative.`}/><div className="split-analysis"><div><span className="eyebrow">5-year cash outlay / before resale</span><div className="big-number">{ownership===null?'Data unavailable':currency(ownership)}</div><p className="data-note">Purchase + running costs. Loan interest, parking, tolls and resale are excluded. No resale forecast is available.</p></div><dl className="finance-lines"><div><dt>Purchase, including first-year insurance</dt><dd>{currency(onRoad)}</dd></div><div><dt>Fuel / energy · estimated</dt><dd>{monthlyFuel===null?'Data unavailable':currency(monthlyFuel*60)}</dd></div><div><dt>Insurance renewals · estimated</dt><dd>{currency(renewalInsurance)}</dd></div><div><dt>Service · estimated</dt><dd>{currency(serviceTotal)}</dd></div><div><dt>Resale value</dt><dd>Data unavailable</dd></div></dl></div><div className="table-scroll tool-space" tabIndex={0} role="region" aria-label="Five year running cost estimate"><table className="data-table"><thead><tr><th>Year</th><th>Service estimate</th><th>Fuel / energy estimate</th><th>Insurance estimate</th></tr></thead><tbody>{service.map((cost,i) => <tr key={i}><th scope="row">Year {i+1}</th><td>{currency(cost)}</td><td>{monthlyFuel===null?'Data unavailable':currency(monthlyFuel*12)}</td><td>{currency(Math.round(price.insurance*insuranceFactors[i]))}{i===0?' · included in purchase':''}</td></tr>)}</tbody></table></div></section>
      <section id="emi" className="chapter" data-tone="financial"><SectionHeader index="07" label="Finance / interactive tool" title="Make the numbers work for you." tone="financial" description={`${variant.name} in ${city.name} · Based on your selected on-road estimate.`}/><div className="split-analysis"><div><InteractiveSlider id="down-payment" label={`Down payment · ${downPayment}%`} value={downPayment} display={currency(downAmount)} min={10} max={70} step={5} onChange={setDownPayment}/><InteractiveSlider id="interest-rate" label="Interest rate" value={interest} display={`${interest}% p.a.`} min={7.5} max={14} step={.25} onChange={setInterest}/><InteractiveSlider id="loan-tenure" label="Tenure" value={years} display={`${years} years / ${years*12} months`} min={1} max={7} onChange={setYears}/></div><div className="finance-result"><span className="eyebrow">Estimated monthly EMI</span><div className="big-number" aria-live="polite">{currency(emi.monthlyEmi)}<small> / month</small></div><dl className="finance-lines"><div><dt>Principal</dt><dd>{currency(emi.loanAmount)}</dd></div><div><dt>Total interest</dt><dd>{currency(emi.totalInterest)}</dd></div><div><dt>Total repayment</dt><dd>{currency(emi.totalPayment)}</dd></div></dl></div></div><details className="repayment"><summary>Yearly repayment schedule</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>Year</th><th>Principal paid</th><th>Interest paid</th><th>Remaining</th></tr></thead><tbody>{schedule.map(row => <tr key={row.year}><th scope="row">{row.year}</th><td>{currency(row.principalPaid)}</td><td>{currency(row.interestPaid)}</td><td>{currency(row.remainingBalance)}</td></tr>)}</tbody></table></div></details></section>
      {rivals.length>0 && <section id="rivals" className="chapter"><SectionHeader index="08" label="Compare" title="The alternatives, side by side."/><div className="table-scroll" tabIndex={0} role="region" aria-label="Rival comparison"><table className="data-table rival-table"><thead><tr><th>At a glance</th>{[model,...rivals.map(r => r.model)].map(car => <th key={car.id}>{car.name}</th>)}</tr></thead><tbody>{[['Starting price',... [model,...rivals.map(r=>r.model)].map(car=>`${lakh(car.priceRangeMin)} Lakh`)],['Crash rating',... [model,...rivals.map(r=>r.model)].map(car=>`${car.safetyRating.stars}★ ${car.safetyRating.agency}`)],['Boot space',... [model,...rivals.map(r=>r.model)].map(car=>specValue(car,/boot/i))],['Seats',... [model,...rivals.map(r=>r.model)].map(car=>car.seatingCapacities.join('/'))]].map(([label,...values])=><tr key={label}><th scope="row">{label}</th>{values.map((value,i)=><td key={i}>{value}</td>)}</tr>)}</tbody></table></div><Link className="text-link" href={`/compare?cars=${[model.slug,...rivals.map(r=>r.model.slug)].slice(0,3).join(',')}`}>View full comparison →</Link></section>}
      <section id="reviews" className="chapter" data-tone="editorial"><SectionHeader index="09" label="The KERB view / editorial" title="Is this the car for you?" tone="editorial" description="Editorial assessment from the vehicle database. A measured KERB road test is not available."/><p className="editorial-copy">{model.kerbVerdict}</p><div className="editorial-lists"><div><h3>What we liked</h3><ul>{model.pros.map(pro=><li key={pro}><span>✓</span>{pro}</li>)}</ul></div><div><h3>What to consider</h3><ul>{model.cons.map(con=><li key={con}><span>△</span>{con}</li>)}</ul></div></div><div className="owner-reviews"><h3>From the owners <span className="muted">/ {reviews.length} reports</span></h3>{reviews.length===0 && <p className="data-note">Owner reports: Data unavailable</p>}{reviews.map(review=><article className="owner-review" key={review.id}><div><strong>{review.author}</strong><p className="data-note">{review.verifiedOwner?'✓ Verified owner':'Owner reported'} · {review.date}<br/>{review.mileageReported && `Owner reported: ${review.mileageReported}`}</p><span className="rating">★ {review.rating} / 5</span></div><div><h3>“{review.title}”</h3><p>{review.body}</p></div></article>)}</div></section>
      <section id="images" className="chapter"><SectionHeader index="10" label="Gallery" title="A closer look." description="Browse the available image library. Use the arrow keys or swipe to change images."/><div className="gallery-stage" tabIndex={0} aria-label="Vehicle gallery; use left and right arrow keys" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();moveImage(1);}if(e.key==='ArrowLeft'){e.preventDefault();moveImage(-1);}}} onTouchStart={e=>{touchStart.current=e.touches[0].clientX;}} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touchStart.current;if(Math.abs(delta)>45)moveImage(delta<0?1:-1);}}><button className="gallery-image-button" onClick={()=>galleryDialog.current?.showModal()} aria-label="Open full-screen gallery"><Image src={currentImage.url} alt={currentImage.altText} fill sizes="(max-width: 768px) 100vw, 1280px"/></button><div className="gallery-controls"><button onClick={()=>moveImage(-1)} aria-label="Previous image">←</button><span>{imageIndex+1} / {gallery.length}</span><button onClick={()=>moveImage(1)} aria-label="Next image">→</button></div></div><div className="thumbnail-rail">{gallery.map((item,index)=><button key={item.id} aria-pressed={index===imageIndex} aria-label={`View image ${index+1}`} onClick={()=>setImageIndex(index)}><Image src={item.url} width={112} height={68} alt=""/></button>)}</div><div className="gallery-colors"><span className="eyebrow">Image library color labels</span>{gallery.map((item,index)=>item.colorName && <button key={item.id} className="filter-option" aria-pressed={imageIndex===index} onClick={()=>setImageIndex(index)}>{item.colorName}</button>)}</div><p className="data-note">Images and color labels are supplied by the existing media library; paint appearance and availability should be confirmed with the manufacturer.</p></section>
      <section id="faqs" className="chapter"><SectionHeader index="11" label="Questions, answered" title={`More about the ${model.name}.`} tone="editorial"/>{model.faqs.map(faq=><div className="faq-row" key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></div>)}{!model.faqs.length && <p className="data-note">Data unavailable</p>}<nav className="dossier-route-links" aria-label="Detailed vehicle research">{topics.filter(item=>item!=='overview').map(item=><Link key={item} href={`${basePath}/${item}`}>{model.name} {item} ↗</Link>)}</nav></section>
      <section id="verdict" className="chapter" data-tone="editorial"><SectionHeader index="12" label="The verdict" title={`Should you buy the ${model.name}?`} tone="editorial"/><div style={{ padding: '32px', background: 'var(--soft-green, var(--secondary))', borderRadius: '16px', marginBottom: '32px' }}><div className="eyebrow" style={{ marginBottom: '16px' }}>KERB Recommendation</div><p className="editorial-copy" style={{ fontSize: 'clamp(18px, 2vw, 24px)' }}>{model.kerbVerdict}</p><div style={{ display: 'flex', gap: '16px', marginTop: '24px', flexWrap: 'wrap' }}><span style={{ padding: '8px 16px', background: 'var(--financial)', color: 'var(--button-ink, #fff)', borderRadius: '8px', fontSize: '13px', fontWeight: 600 }}>★ {model.rating}/5 Rating</span><span style={{ padding: '8px 16px', background: 'var(--safety)', color: '#fff', borderRadius: '8px', fontSize: '13px', fontWeight: 600 }}>{model.safetyRating.stars}★ {model.safetyRating.agency}</span></div></div><div className="editorial-lists"><div><h3>What we liked</h3><ul>{model.pros.map(pro=><li key={pro}><span>✓</span>{pro}</li>)}</ul></div><div><h3>What to consider</h3><ul>{model.cons.map(con=><li key={con}><span>△</span>{con}</li>)}</ul></div></div></section>
      <section id="similar" className="chapter"><SectionHeader index="13" label="Alternatives" title="Similar cars you might consider"/><div className="vehicle-grid">{rivals.map(rival => <VehicleCard key={rival.model.id} model={rival.model} make={rival.make} />)}{getAllModels().filter(m => m.makeId === model.makeId && m.id !== model.id).slice(0, Math.max(0, 4 - rivals.length)).map(m => { const mMake = initialData.make; return <VehicleCard key={m.id} model={m} make={mMake} />; })}</div></section>
      <section id="budget" className="chapter"><SectionHeader index="14" label="Same budget" title="More options at this price"/><div className="vehicle-grid">{getAllModels().filter(m => Math.abs(m.priceRangeMin - model.priceRangeMin) <= 200000 && m.id !== model.id).slice(0, 4).map(m => { const mMake = getAllMakes().find(mk => mk.id === m.makeId)!; return <VehicleCard key={m.id} model={m} make={mMake} />; })}</div></section>
      <section id="enquiry" className="chapter"><SectionHeader index="15" label="Enquiry" title={`Interested in the ${model.name}?`}/><form onSubmit={e => { e.preventDefault(); alert('Enquiry submitted!'); }} style={{ padding: '32px', background: 'var(--soft-green, var(--secondary))', borderRadius: '16px' }}><div style={{ display: 'grid', gap: '16px', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', marginBottom: '24px' }}><input type="text" placeholder="Name" required style={{ padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)' }} /><input type="tel" placeholder="Phone" required style={{ padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)' }} /><select required style={{ padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)' }}><option value="">Select City</option>{cities.map(c => <option key={c.id} value={c.slug}>{c.name}</option>)}</select><input type="hidden" name="model" value={model.id} /></div><button type="submit" className="action" style={{ width: '100%', background: 'var(--financial)', color: '#fff' }}>Get Best Price</button></form></section>
    </div>
    <aside className="dossier-mobile-actions" aria-label="Quick vehicle actions"><a href="#price"><small>Est. on-road</small><strong>{lakh(onRoad)}L</strong></a><Link href={`/compare?cars=${model.slug}`}>Compare</Link><a href="#emi">EMI →</a></aside>
    <dialog ref={galleryDialog} className="gallery-dialog" aria-label="Vehicle image gallery" onClose={()=>setZoom(false)} onKeyDown={event=>{if(event.key==='ArrowRight')moveImage(1);if(event.key==='ArrowLeft')moveImage(-1);}}><div className="dialog-top"><span>{make.name} {model.name} · {imageIndex+1}/{gallery.length}</span><button className="action secondary" onClick={()=>galleryDialog.current?.close()}>Close ×</button></div><div className={`fullscreen-image ${zoom?'zoomed':''}`} onTouchStart={e=>{touchStart.current=e.touches[0].clientX;}} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touchStart.current;if(Math.abs(delta)>45)moveImage(delta<0?1:-1);}}><Image src={currentImage.url} alt={currentImage.altText} fill sizes="100vw"/></div><div className="actions"><button className="action secondary" onClick={()=>moveImage(-1)}>← Previous</button><button className="action secondary" aria-pressed={zoom} onClick={()=>setZoom(!zoom)}>{zoom?'− Zoom out':'+ Zoom in'}</button><button className="action secondary" onClick={()=>moveImage(1)}>Next →</button></div></dialog>
  </div>;
};
export default CarShowroom;
